export const movieCards = [
  {
    type: "trending",
    bg: "bg-[#141414]",
    title: "Top Ciencia Ficción\nEsta Semana",
    sub: "EN TENDENCIA",
    hasJoin: true,
    avatarLetters: ["S", "F", "X"],
    avatarColors: ["#3a8a5e", "#3a6ea5", "#7b5ea7"],
  },
  {
    type: "premiere",
    bgStyle: "linear-gradient(160deg,#8b0000 60%,#2a0000)",
    title: "Nuevos Lanzamientos",
    sub: "películas recién agregadas",
    badge: "NUEVO",
  },
  {
    type: "event",
    bgStyle: "linear-gradient(160deg,#1a1a2e 40%,#3a3a7b)",
    title: "28 Abril\nNoche de Cine",
    sub: "WATCH PARTY",
    hasJoin: true,
    dateTag: "28 Abril",
  },
  {
    type: "genre",
    bgStyle: "linear-gradient(160deg,#0f2027 60%,#203a43)",
    title: "Clásicos de Acción",
    sub: "éxitos explosivos",
    badge: "HOT",
  },
  {
    type: "community",
    bg: "bg-[#1c1c1c]",
    title: "Amantes del Cine\nComunidad",
    sub: "GRUPOS Y RESEÑAS",
    hasJoin: true,
    avatarLetters: ["M", "C", "R"],
    avatarColors: ["#e07b39", "#3a8a5e", "#7b5ea7"],
  },
  {
    type: "festival",
    bgStyle: "linear-gradient(160deg,#2a1a3a 50%,#0d0615)",
    title: "Selección Cannes\n2026",
    sub: "FESTIVAL DE CINE",
    hasJoin: true,
    dateTag: "Mayo 2026",
  },
];
