export const videos = [
  {
    id: 1,
    title: "Crazy Night with my Mom",
    user: "marieparis",
    verified: true,
    duration: "3:03",
    tag: "Recommended",
    gradient: "from-purple-900 via-pink-800 to-orange-600",
    emoji: "🎡",
    desc: "Una noche increíble llena de luces y diversión.",
  },
  {
    id: 2,
    title: "This Dog Is The Cutest, Grumpiest Old Man",
    user: "The Dodo",
    verified: true,
    duration: "4:19",
    tag: "Recommended",
    gradient: "from-red-700 via-red-600 to-red-500",
    emoji: "🐾",
    desc: "El perro más gruñón y adorable del internet.",
  },
  {
    id: 3,
    title: "Let's Go Skate III Video",
    user: "loanmak",
    verified: false,
    duration: "1:32",
    tag: "Recommended",
    gradient: "from-gray-700 via-gray-600 to-gray-500",
    emoji: "🛹",
    desc: "Trucos imposibles en las calles de la ciudad.",
  },
  {
    id: 4,
    title: "200 Days Around the World",
    user: "kalvisuals",
    verified: true,
    duration: "6:28",
    tag: "Recommended",
    gradient: "from-red-800 via-orange-700 to-yellow-600",
    emoji: "🌍",
    desc: "Un viaje épico por 30 países en 200 días.",
  },
  {
    id: 5,
    title: "Late Night Vibes",
    user: "nightcrew",
    verified: false,
    duration: "2:03",
    tag: "",
    gradient: "from-indigo-900 via-purple-800 to-pink-700",
    emoji: "🌙",
    desc: "La ciudad nunca duerme, y nosotros tampoco.",
  },
  {
    id: 6,
    title: "Falcon Heavy Launch",
    user: "spacex",
    verified: true,
    duration: "3:12",
    tag: "",
    gradient: "from-slate-900 via-blue-900 to-slate-700",
    emoji: "🚀",
    desc: "El cohete más poderoso vuelve a despegar.",
  },
  {
    id: 7,
    title: "Coastal Cliffs Adventure",
    user: "wanderer",
    verified: false,
    duration: "0:43",
    tag: "",
    gradient: "from-teal-800 via-cyan-700 to-blue-600",
    emoji: "🏔️",
    desc: "Acantilados costeros al borde del mundo.",
  },
  {
    id: 8,
    title: "Owl in the Wild",
    user: "naturelens",
    verified: true,
    duration: "2:11",
    tag: "",
    gradient: "from-gray-800 via-stone-700 to-zinc-600",
    emoji: "🦉",
    desc: "Una lechuza salvaje filmada en su hábitat natural.",
  },
];
